#!/bin/bash

set -o errexit	# set -e
set -o nounset	# set -u

eval CONFIG_DIR="~/config"

# Disable one warning, but fail on any others
EXTRA_CFLAGS="-Wno-unused-result -Werror"

function get_config_location()
{
	local TEST="/$1"

	while [ -n "$TEST" ]; do
		if [ -f "$CONFIG_DIR${TEST}.txt" ]; then
			echo "$CONFIG_DIR${TEST}.txt"
			return
		fi
		TEST="${TEST%/*}"
	done

	echo "$CONFIG_DIR/default.txt"
}

function _run_build()
{
	if [[ $# -ne 4 ]]; then
		echo "Illegal arguments passed."
		return
	fi
	BRANCH="$1"
	LEN="$2"
	FILE="$3"
	CONFIG_DIR="$4"

	echo "-------------------------------------------------------------------------------"
	echo "BRANCH:         https://github.com/neomutt/neomutt/tree/$BRANCH"
	echo "COMMIT:         https://github.com/neomutt/neomutt/commit/$(git rev-parse HEAD)"
	echo "CONFIG FILE:    https://github.com/neomutt/travis-build/blob/master/${FILE#$CONFIG_DIR/}"
	echo "CONFIGURATIONS: $LEN"
	echo "-------------------------------------------------------------------------------"
	BUILD_COUNT=0
	while read CONFIG; do
		: $((BUILD_COUNT++))
		echo "BUILD: $BUILD_COUNT/$LEN"
		if [ -n "$CONFIG" ]; then
			echo "$CONFIG" | fmt -w 75 | sed 's/^/    /'
		else
			echo "    <no options>"
		fi
		echo
		echo -en "travis_fold:start:configure.$BUILD_COUNT\\r"
		echo "Configure"
		git clean -xdfq
		if ! ./configure.autosetup --disable-doc $CONFIG; then
			echo "-------------------------------------------------------------------------------"
			[ -f config.log ] && cat config.log
			exit 1
		fi
		echo -en "travis_fold:end:configure.$BUILD_COUNT\\r"
		echo -en "travis_fold:start:make.$BUILD_COUNT\\r"
		echo "Build"
		make -j2 EXTRA_CFLAGS="$EXTRA_CFLAGS" || exit 1
		echo
		echo -en "travis_fold:end:make.$BUILD_COUNT\\r"
		echo -en "travis_fold:start:version.$BUILD_COUNT\\r"
		echo "Version"
		./neomutt -v
		echo -en "travis_fold:end:version.$BUILD_COUNT\\r"
		echo
		echo "-------------------------------------------------------------------------------"
	done < "$FILE"
}


if [ -n "${TRAVIS_BRANCH:-}" ]; then
	BRANCH="$TRAVIS_BRANCH"
else
	BRANCH=$(git rev-parse --abbrev-ref HEAD)
fi

if [[ "${TRAVIS_PULL_REQUEST:-}" =~ ^[0-9]+$ ]]; then
	FILE="$CONFIG_DIR/pull-request.txt"
else
	FILE=$(get_config_location $BRANCH)
fi

LEN=$(wc -l "$FILE" | cut -d' ' -f1)

_run_build "$BRANCH" "$LEN" "$FILE" "$CONFIG_DIR"

# if [[ $BRANCH = "master" && ! "${TRAVIS_PULL_REQUEST:-}" =~ ^[0-9]+$ ]]; then
# 	# Do a full build and test it
# fi

if [[ $BRANCH = "feature/unit-test" ]]; then
	echo "-------------------------------------------------------------------------------"
	echo "TEST"
	./neomutt -T
	echo "-------------------------------------------------------------------------------"
fi

echo Success
exit 0

